import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" data-lt-installed="true">
      <body  data-new-gr-c-s-check-loaded="14.1115.0" data-gr-ext-installed cz-shortcut-listen="true" className={inter.className}>
        {children}
        <BootstrapClient></BootstrapClient>
        </body>
    </html>
  );
}
